/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _404Route } from '../pages/_404';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/_404': (typeof _404Route)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/_404': (typeof _404Route)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
